theme: jekyll-theme-slate 
title: Summary of Mystical Theology of the Eastern Church by V. Lossky
description: Each chapter will have a summary  

avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
